# Generated by Django 4.1.4 on 2022-12-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=32, verbose_name='pwd')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='UpdateTime')),
            ],
        ),
    ]
