# Generated by Django 4.1.4 on 2022-12-25 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='blog title')),
                ('category', models.CharField(max_length=20, verbose_name='blog category')),
                ('limit', models.CharField(max_length=20, verbose_name='blog limit')),
                ('introduce', models.CharField(max_length=90, verbose_name='blog introduction')),
                ('content', models.TextField(verbose_name='blog content')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
    ]
